### ISSUE TITLE
Add support for unordered_map

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/sdbusplus#11]
The sdbusplus bindings currently support map.  Add support for unordered_map also.

**Comment by williamspatrick** [comment]
@milindur - I'm also considering changing the server bindings to generate unordered_map instead of map.  Do you have any preference?  I suspect that unordered_map may result in smaller code generation and so for our embedded system this is desirable.  I could certainly leave it as a configure option.

**Comment by milindur** [comment]
@williamspatrick Hmm, in most cases unordered_map should be okay. Maybe we just can use `dict` and e.g. `unordered_dict` in the YAML? In this case it would be possible to decide for every usage.

**Comment by edtanous** [comment]
This issue has been resolved for a while now, and includes relevant unit tests.  This should be able to be closed.
