### ISSUE TITLE
Better to use lowercase namespace for generated C++ code

### ISSUE THREAD

**Issue by mine260309** [openbmc/sdbusplus#13]
The current generated code uses the path name as the namespace name, e.g. `xyz/openbmc_project/Inventory/Item/MemoryBuffer.interface.yaml` would generate namespace like:

```
namespace sdbusplus
{
namespace xyz
{
namespace openbmc_project
{
namespace Inventory
{
namespace Item
{
namespace server
{
...
```

Is it better to use lowercase for them? E.g. `sdbusplus::xyz::openbmc_project::inventory::item::server::`?

Note: our [cpp-style-guide](https://github.com/openbmc/docs/blob/master/cpp-style-and-conventions.md#namespaces) indicates that
>Namespaces should be lower_snake_case.

**Comment by williamspatrick** [comment]
This has been fixed in later versions.  The "new namespace" uses snake-case as much as possible.
