### ISSUE TITLE
Interface enum example produces invalid tuple

### ISSUE THREAD

**Issue by hojalot** [openbmc/sdbusplus#18]
In docs/interface.md, example methods have ``type: struct[enum[self.Suit], byte]`` which results in stdbus++ server.hpp output:
```
virtual void moveToTop(
            std::tuple<enum<self.Suit>, uint8_t> card) = 0;
```

When compiled with a trivial main.cc that includes the hpp fle, the error is:
```
g++ main.cc server.cc -o server
In file included from main.cc:15:0:
server.hpp:66:52: error: template argument 1 is invalid
         virtual std::tuple<enum<self.Suit>, uint8_t> lookAtTop(
```

Adding some instrumentation to ``tools/sdbusplus/property.py`` seems to show that ``cppTypeParam()`` is never called.  This is the method in which the ``enum<`` and ``self.`` are removed.

**Comment by williamspatrick** [comment]
I'm pretty sure this was fixed.  There were a number of commits to get there but anything after f7e2159d7a79fa22e45739f0778566cb94136cb2 should work.
