### ISSUE TITLE
request_name does not propagate error state/return code

### ISSUE THREAD

**Issue by aiQon** [openbmc/sdbusplus#21]
I just noticed that if I try to request a name on  dbus with `sdbusplus::bus::request_name`, I do not get a return code from the underlying implementation. This conveniently hid a bug with policy configuration in my case.
Is there a reason for doing so or might a simple `return` do the trick in the [implementation](https://github.com/openbmc/sdbusplus/blob/master/sdbusplus/bus.hpp.in#L189)?

**Comment by whame** [comment]
Yeah, I just realized that as well. There are also other places where return codes are completely ignored (for instance [sd_bus_open](https://github.com/openbmc/sdbusplus/blob/ca46b9d2e958d1e4b392265f656f782899c2de1d/sdbusplus/bus.hpp.in#L488), [sd_bus_open_user](https://github.com/openbmc/sdbusplus/blob/ca46b9d2e958d1e4b392265f656f782899c2de1d/sdbusplus/bus.hpp.in#L495) and [sd_bus_open_system](https://github.com/openbmc/sdbusplus/blob/ca46b9d2e958d1e4b392265f656f782899c2de1d/sdbusplus/bus.hpp.in#L502))

These should certainly be fixed. However, checking request_name was sufficient for my application. I have pushed the changes to their Gerrit instance.

**Comment by wak-google** [comment]
I've been doing some work to try and fix all of these but it takes time to recover from the fallout where we depend on the error case not failing. I suspect this one and quite a few others will be trivial though.

**Comment by williamspatrick** [comment]
`request_name` now checks return code.  Many others have been fixed as well.  Please report any new ones.
