### ISSUE TITLE
Cannot extract errno from SdBusError

### ISSUE THREAD

**Issue by amboar** [openbmc/sdbusplus#22]
As it stands we expose the following public interfaces:

https://github.com/openbmc/sdbusplus/blob/5b701c66a808d5b80436c71cc9ce8576ad3dfda6/sdbusplus/exception.hpp#L45
https://github.com/openbmc/sdbusplus/blob/5b701c66a808d5b80436c71cc9ce8576ad3dfda6/sdbusplus/exception.hpp#L46
https://github.com/openbmc/sdbusplus/blob/5b701c66a808d5b80436c71cc9ce8576ad3dfda6/sdbusplus/exception.hpp#L47

and the `sd_bus_error` instance is private:

https://github.com/openbmc/sdbusplus/blob/5b701c66a808d5b80436c71cc9ce8576ad3dfda6/sdbusplus/exception.hpp#L50

Which means if we want to extract and use the errno for anything we have to do something truly awful:

https://gerrit.openbmc-project.xyz/#/c/openbmc/openpower-host-ipmi-flash/+/12502/3/hiomap.cpp@62

Please fix the interface so we can extract errno without losing our sanity. The translation code in the patch above is beyond a joke.

**Comment by bradbishop** [comment]
We had this ability - it was removed with https://github.com/openbmc/sdbusplus/commit/fac43a650e59e873688d5fc6e06b5bdc88ba0546

@vmauery can you help me remember why we did this?  I vaguely remember something didn't work quite right.

@wak-google @anoo1 fyi....

**Comment by wak-google** [comment]
We can add this back by doing our own thing in SdEventError to emulate the old behavior of std::system_error. Ideally applications use the error name() because that is intended to be a unique, parse-able string and it's how sd_bus creates the errno in the first place.

Would it be sufficient to add back the .code() method that is identical to the std::system_error variant?

**Comment by amboar** [comment]
I'd be happy to have a .code() that calls through and returns the result of `sd_bus_error_get_errno()`.

**Comment by anoo1** [comment]
Proposed new .code() method - https://gerrit.openbmc-project.xyz/#/c/openbmc/sdbusplus/+/13064/
