### ISSUE TITLE
configure: Fixup cross compilation

### ISSUE THREAD

**Issue by wak-google** [openbmc/sdbusplus#25]
Make sure we can build the native sdbus++ tool and use it with a cross compiled build to generate the example binaries for a target platform

**Comment by wak-google** [comment]
https://github.com/openbmc/sdbusplus/commit/ad7e686b5563a146728aa9477f6e814dc0a3cbd4
helps with this issue but it doesn't really resolve it properly.

**Comment by manojkiraneda** [comment]
> Make sure we can build the native sdbus++ tool and use it with a cross compiled build to generate the example binaries for a target platform

@wak-google the commit [ad7e686](https://github.com/openbmc/sdbusplus/commit/ad7e686b5563a146728aa9477f6e814dc0a3cbd4) makes sure that if the user disables the sdbus++ tool, we should not build any example binaries using the sdbus++ tool, there  by avoiding the build failure.And also,the build works fine if the sdbus++ app is enabled.

can you explain the issue a bit more ? i did quite not understand it ?

**Comment by wak-google** [comment]
The issue is that our software isn't very friendly to typical build environments where you have {build,host} targets. If you are targeting `host`, you will want to build all of the necessary native tooling targeting `build` that is needed to build all of the `host` software. sdbus++ is the only part of sdbusplus needed as a native `build` target, and typically the only piece not needed as a host dependency. It should therefore be possible to build sdbus++ without everything else and vice versa.

**Comment by williamspatrick** [comment]
I split out the sdbus++ install as a standard python setuptools under f934ca3083f3a9a1a3f3a8aba1d85c317bf9d24f .  Please let me know if this doesn't resolve any issues here as I think it does.
