### ISSUE TITLE
configure: Improve c++ error when autoconf-archive is too old

### ISSUE THREAD

**Issue by wak-google** [openbmc/sdbusplus#26]
We can use AX_CXX_COMPILE_STDCXX() instead of AX_CXX_COMPILE_STDCXX_1{4,7}()

We get errors like:
configure.ac:24: error: invalid first argument `20' to AX_CXX_COMPILE_STDCXX

Instead of:
./configure: line 5132: syntax error near unexpected token `noext'
./configure: line 5132: `AX_CXX_COMPILE_STDCXX_20(noext)'

**Comment by williamspatrick** [comment]
I'm removing autotools entirely with I57027dd772b088d1d3659b23d5a1431a31b9aaa2.
