### ISSUE TITLE
Running example calculator crashes with: sd_bus_request_name: org.freedesktop.DBus.Error.InvalidArgs: Invalid argument

### ISSUE THREAD

**Issue by BrainStone** [openbmc/sdbusplus#32]
Hello there!

I'm not sure if that's an issue with the library or me not quite understanding how the dbus works.

So just running the example calculator crashes the program and it gives me this error message:

```
terminate called after throwing an instance of 'sdbusplus::exception::SdBusError'
  what():  sd_bus_request_name: org.freedesktop.DBus.Error.InvalidArgs: Invalid argument
Aborted
```

Investigating the error turns out the error is thrown right here: https://github.com/openbmc/sdbusplus/blob/c14699f63e909ed6d8599e65503ee9c1e3a104d6/sdbusplus/bus.hpp.in#L229-L236 (line 234 to be exact)

I personally have the feeling that the bus name needs to be registered somewhere beforehand, before it can be used. If that's the case, would it be possible to add an example for that too?

**Comment by BrainStone** [comment]
@wak-google any idea on this?

**Comment by BrainStone** [comment]
This issues was caused by the user bus not existing. So just a local issue.

**Comment by athkar123** [comment]
@BrainStone How did you resolve this?
