### ISSUE TITLE
Allow compiling library statically

### ISSUE THREAD

**Issue by BrainStone** [openbmc/sdbusplus#33]
Due to some restrictions and uncertainties on the target system, I'd like to be able to statically link this library into my program, so I can make sure it won't crash because the target system doesn't have the dynamic library files.

Alternatively a simple way (like a dpkg package) to distrubute the shared library files on the target system without having to compile them there would work for me too.

**Comment by BrainStone** [comment]
Seems like #31 goes in the same direction.

**Comment by wak-google** [comment]
Well you can already distribute the tooling separate from the library, using the provided configure flags to build the tooling on the host and then build the library for the target. It probably doesn't support building as a static library but we could implement that.

**Comment by BrainStone** [comment]
That would be very nice. Statically linking against it makes my live a whole lot easier.  
It would also be nice if it would work with `pkg-config` in the sense that I can pass the program the `--static` flag and it gives me the right flags to link it statically. 

And I'm more interested in distributing the library (not publically).

And lastly, is there a way to talk to you/the dev team somewhere other than GitHub? I'd prefer not having to make an issue for every itty bitty thing I come across while using this.

**Comment by williamspatrick** [comment]
I think this was previously implemented in the autotools set up but this issue was never closed.

I recently added meson build support and @wak-google made a change to ensure it builds a static library if desired (meson option `-Ddefault_library=static`).

@BrainStone - outside of GH issues, you can get real time communication on freenode IRC #openbmc for almost any repository under the openbmc github project.

**Comment by BrainStone** [comment]
Thank you for the follow up!

I'll keep that in mind. I'll see if I'll revisit the project I use the library in.
