### ISSUE TITLE
Docs of the YAML format are not up to date

### ISSUE THREAD

**Issue by BrainStone** [openbmc/sdbusplus#34]
It seems like the docs on the available flags for the YAML format are not up to date.

For example it claims that the only available flag is `const`. But `readonly` is available too.  
See https://github.com/openbmc/sdbusplus/blob/c08cf5283b80a071d19506d9a462f6c69e1797f1/docs/interface.md#properties

**Comment by williamspatrick** [comment]
This was resolved as part of #48.  (Readonly wasn't previously supported correctly but is now and is documented.)
