### ISSUE TITLE
Are there ASIO unit tests or mock classes anywhere for sdbusplus? Has it been tested in an SMP environment?

### ISSUE THREAD

**Issue by IAmWilfredSmith** [openbmc/sdbusplus#37]
OpenBMC relies very heavily this body of code. I always get concerned when something foundational has no test cases to prove that it functions as promised. Before I go off tilting at windmills, I'd like to know if the fuzz, boundary and logic test cases exist somewhere and/or the mock classes. Thanks in advance.

**Comment by IAmWilfredSmith** [comment]
It looks like there are Google Test cases here, but nothing for ASIO?

**Comment by amboar** [comment]
For what it's worth you can run `./bootstrap.sh && ./configure --enable-code-coverage && make check-code-coverage` to build a report of all lines touched by the tests. This may help answer the question about ASIO (I don't know off the top of my head)

**Comment by IAmWilfredSmith** [comment]
At least in the test folder, there's no mention of Asio whatsoever. I also don't see any mention of post or dispatch or io_context/io_service.

**Comment by IAmWilfredSmith** [comment]
Another issue: I'd like to run this on the target environment and this quickly goes beyond my hardware's space limits.
