### ISSUE TITLE
running "make check" have error : ld returned 1 exit status

### ISSUE THREAD

**Issue by Journey-x** [openbmc/sdbusplus#39]
I'm running  tests in SDK . In sdbusplus, follow the steps:
./bootstrap.sh
./configure ${CONFIGURE_FLAGS} --enable-oe-sdk
make check

when "make check", something wrong:

Making check in .
make[1]: Entering directory `/home/root1/sdbusplus'
make[1]: Leaving directory `/home/root1/sdbusplus'
Making check in tools
make[1]: Entering directory `/home/root1/sdbusplus/tools'
running build
make[1]: Leaving directory `/home/root1/sdbusplus/tools'
Making check in example
make[1]: Entering directory `/home/root1/sdbusplus/example'
make  check-am
make[2]: Entering directory `/home/root1/sdbusplus/example'
  CXX      list_users-list-users.o
  CXXLD    list-users
  CXX      calculator_server-calculator-server.o
  CXX      net/poettering/Calculator/calculator_server-server.o
  CXXLD    calculator-server
make[2]: Leaving directory `/home/root1/sdbusplus/example'
make[1]: Leaving directory `/home/root1/sdbusplus/example'
Making check in test
make[1]: Entering directory `/home/root1/sdbusplus/test'
make  bus_list_names bus_match exception_sdbus_error message_append message_read message_native_types message_types utility_tuple_to_array utility_type_traits vtable_vtable timer
make[2]: Entering directory `/home/root1/sdbusplus/test'
  CXX      bus/list_names.o
  CXXLD    bus_list_names
/home/root1/sdk/sysroots/x86_64-oesdk-linux/usr/libexec/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/9.2.0/real-ld: /home/root1/sdk/sysroots/armv5e-openbmc-linux-gnueabi/usr/lib/libgmock_main.a(gmock_main.cc.o): in function `main':
/usr/src/debug/googletest/1.8.1-r0/git/googlemock/src/gmock_main.cc:52: undefined reference to `testing::InitGoogleMock(int*, char**)'
collect2: error: ld returned 1 exit status
make[2]: *** [bus_list_names] Error 1
make[2]: Leaving directory `/home/root1/sdbusplus/test'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/root1/sdbusplus/test'
make: *** [check-recursive] Error 1

**Comment by williamspatrick** [comment]
We have moved to meson-build now.  Can you recreate with latest code and meson?
