### ISSUE TITLE
Wait for an object path to be created

### ISSUE THREAD

**Issue by ytmhub** [openbmc/sdbusplus#43]
[phosphor-objmgr](https://github.com/openbmc/phosphor-objmgr) provides [mapper_wait_async](https://github.com/openbmc/phosphor-objmgr/blob/master/libmapper/mapper.c#L308) that waits for an object path to be created.

Is there a similar functionality here?

This would be very useful when having to handle sensors that are added/removed dynamically, for example.

**Comment by williamspatrick** [comment]
@ytmhub - Would you mind expanding on what you're interested in?  The mapper APIs are provided by a particular daemon (objmgr) to more easily consume some signals it is generating.  Are you just looking for a C++ API for this or you don't want to link against the objmgr library?

**Comment by ytmhub** [comment]
Well I'm not looking for a specific function that does exactly what mapper wait does, I just wanted to know if there's an idiomatic way of implementing 'mapper_wait_async' with sdbusplus API, so I can plug the a wait callback (implemented as a lambda) into an existing io_context. Since I'm not super familiar with it yet, I wanted some direction.

I any case, I do have sort of a solution (with a minor issue I still need to figure out) by linking against objmgr (which I wanted to avoid at first, in order to have something more generic, that can listen for other signals as well), and using sd_event_wrapper, but as stated above, I just wanted to know if there's a cleaner and more "C++-y" way to do that.
