### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by BrainStone** [openbmc/sdbusplus#47]
I saw you switched to the new meson build system.  
Since that is not a common build system I highly recommend you add documentation on how to properly build the project.

**Comment by mdmillerii** [comment]
Meson has a decent tutoral and manual wiki https://mesonbuild.com/.
That said I noticed a reference to

**Comment by BrainStone** [comment]
On the note that there's a tutorial on their homepage.  
That's great and all. But why not document it in the README like any other project so people don't have to jump through hoops to build the library? Building the library should be made easy for the user of the library. That makes them more likely to actually use it, which I presume is the overall goal.

**Comment by mdmillerii** [comment]
I agree it was missed in the conversion that's why I pointed out other related erros.   It's 1:30am so I'm not proposing a patch at this time.  

I'd suggest installing meson from your distribution or following their website and also nitro (python3 is already a prerequisite) then try the quick start https://mesonbuild.com/Quick-guide.html#compiling-a-meson-project .

**Comment by williamspatrick** [comment]
remote:   https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/34609 README: add build instructions (meson/python)

**Comment by williamspatrick** [comment]
@mdmillerii - I'm not seeing anything in our README that references autotools.  Can you point me to it?  I might just be blind.

**Comment by williamspatrick** [comment]
Oh.  I guess I need to update the dependency to have meson instead.

**Comment by williamspatrick** [comment]
remote:   https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/34610 README: remove autoconf from dependency

**Comment by mdmillerii** [comment]
>  and point to examples/Makefile.am

**Comment by williamspatrick** [comment]
Merged.
