### ISSUE TITLE
Add readonly property

### ISSUE THREAD

**Issue by BrainStone** [openbmc/sdbusplus#48]
Add a property that prevents the value from being changed by the client but can be changed by the application.

Making this as discussed on IRC.

**Comment by williamspatrick** [comment]
remote:   https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/34607 sdbus++: support 'readonly' flag

**Comment by BrainStone** [comment]
When can I expect this to be merged here?

**Comment by williamspatrick** [comment]
It takes a few (business) days to get things reviewed.  I would suspect before Thursday end of day (US time).

**Comment by BrainStone** [comment]
Awesome. Thank you very much!

**Comment by williamspatrick** [comment]
Merged.
