### ISSUE TITLE
long build directory paths cause sdbusplus compile failures

### ISSUE THREAD

**Issue by geissonator** [openbmc/sdbusplus#49]
We've got a fairly lengthy jenkins build path in our downstream code and for some reason the latest poky or meta-openembedded bumps are now causing build failures in sdbusplus because of it.

```
| Assembler messages:
| Fatal error: can't create test/test-server.p/_home_fspcibld_openbmc-dev-jenkins_workspace_OpenBMC-Dev_build_github-private_ghe-openbmc-rebase-test-builds_label_x86-docker-builder_target_rainier_build_work_armv7ahf-vfpv4d16-openbmc-linux-gnueabi_sdbusplus_1.0+gitAUTOINC+2be0e17331-r1_build_test_server_Test_server.cpp.o: File name too long
```

It seems this sdbusplus test cases bases a generated file name off of the directory path. Any way we could shorten this up?

**Comment by williamspatrick** [comment]
This is a problem with how Meson creates files names on generated code.  In the short-term I've put up a commit to disable `tests` and `examples` when building under Yocto.  In the long-term, I've revamped how to deal with sdbus++ generated files under meson and need to convert sdbusplus to use that as well (see phosphor-dbus-interfaces).

https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/36505 sdbusplus: disable tests and examples
