### ISSUE TITLE
Incorrect mappings in enums with On and Off

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/sdbusplus#5]
When I run sdbus++ on the yaml file that contains Off and On ( Physical.interface.yaml in phosphor-dbus-interfaces ), the generated code produces -

        enum class Action
        {
            False,
            True,
            Blink,
        };

What it needs to have is 

        enum class Action
        {
            Off,,
            On,
            Blink,
        };

**Comment by williamspatrick** [comment]
This is behavior of the PyYAML parsing library and nothing I can do about it.

```
>>> import yaml
>>> yaml.safe_load("On")
True
>>> yaml.safe_load("'On'")
'On'
>>> yaml.safe_load("Foo")
'Foo'
```

Any of these "reserved" words need to be wrapped in a single quote when used in YAML.

Other projects have ran into the same problem:
https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#true-false-yes-no-on-off

**Comment by vishwabmc** [comment]
Pushed https://gerrit.openbmc-project.xyz/1326
