### ISSUE TITLE
message::read doesn't handle multiple enums in a variant

### ISSUE THREAD

**Issue by jonathan-doman** [openbmc/sdbusplus#52]
For interfaces with properties of different enum types (right now I'm working with `xyz.openbmc_project.State.Host`), the auto-generated binding contains a `PropertiesVariant` with multiple C++ enum types. But it seems like the underlying `message::read` infrastructure cannot properly distinguish between the enums because they all look like strings on D-Bus. So, for example, if you try to `read` out a `PropertiesVariant` on the `org.freedesktop.DBus.Properties.PropertiesChanged` signal message, it will (I think) try to convert all the strings to the first enum type in the variant, and throw an exception from the underlying `convert_from_string`.

I think most code just ignores the auto-generated enums and works with strings, so this is perhaps a rare edge case, but it would be nice to support if feasible. Maybe [here](https://github.com/openbmc/sdbusplus/blob/master/include/sdbusplus/message/read.hpp#L421), an error could be handled by trying the next type in the variant?

**Comment by williamspatrick** [comment]
Interesting find.  I’ll take a look and get it fixed.

**Comment by williamspatrick** [comment]
This was a pretty complex fix so it has taken me quite a while to get to it.  Available here: https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/45001
