### ISSUE TITLE
Exit bug

### ISSUE THREAD

**Issue by furious92** [openbmc/sdbusplus#56]
There is a bug in the `include/sdbusplus/asio/connection.hpp` in the  `read_wait` function. If we cancel our loop in the callback function we have to stop waiting for incoming message, so we have to quit from read_wait function.  But in your code you schedule another reading. The possible solution could be:
```
    void read_wait() 
    {
        socket.async_read_some(  
            boost::asio::null_buffers(),  
            [&](const boost::system::error_code& ec, std::size_t) {  
                if (ec)  
                {  
                    return;  
                }
                if (process_discard())  
                {  
                    read_immediate();  
                }  
                else  
                {  
                    read_wait();  
                }  
            });  
    }  
```

**Comment by vmauery** [comment]
I added a change for review:  https://gerrit.openbmc-project.xyz/c/openbmc/sdbusplus/+/39070
