### ISSUE TITLE
Uncertain on how we can listen to signals

### ISSUE THREAD

**Issue by Noomaok** [openbmc/sdbusplus#58]
Hi, I am trying to use this library to build some apps that can communicate using dbus interfaces. I based my work on your boost asio example since I want to use it to do some extra stuff later on.

I am facing a problem concerning signals. I see a lot of stuff to set and emit signals from the server side (`register_signal` and `signal_property` for dbus_interface but also `new_signal` from the bus class). 
First, I am not sure which one I should use. It feels like it will be more natural to use functions from the dbus_interface class.
Also, I didn't find how I am supposed to implement signals on the client side. Like how can I tell my application to wait and do something for a particular signal ?
The closest thing I could find was the match class, but I don't really know how to use it properly.

I am still a beginner with dbus and the stuff around it so I may have misunderstood something.

Thank you in advance if you can help me resolve this issue.

**Comment by williamspatrick** [comment]
You may want to look at code from this query for examples: https://github.com/search?q=org%3Aopenbmc+sdbusplus%3A%3Abus%3A%3Amatch&type=code

Match is what you are looking for. There isn’t any way currently with dbus to say sequentially “wait until signal X happens and then continue this code”. That programming model is something you could maybe do with C++ coroutines but I haven’t implemented support for that yet. Typically with dbus, everything is callback oriented. Match has a match rule (what kind of signal are you looking for) and a callback. Your callback will be called by the process loop whenever a signal matching your request comes in.

**Comment by Noomaok** [comment]
Thank you for your quick response.
I was able to use signals with your explanation and by exploring the code present in others repository.

It would be beneficial to add an example in the `asio-example.cpp` file for future users I think.

Anyway, have a great day.
