### ISSUE TITLE
(Question) Unpacking variants in a signal handler, std::bad_variant_access

### ISSUE THREAD

**Issue by vsabadazh** [openbmc/sdbusplus#59]
Dear colleagues, 
I am writing in hope that you would help me address the following problem, because I am out of ideas and debugging does not give much of a result. 

In my application I am using sdbusplus for communicating with BlueZ stack via D-Bus. When processing scan results in `PropertiesChanged` signal handler (which has signature `sa{sv}as`), we are supposed to `read()` into three variables, the first one being a `string`, second a `map` and the third one a `vector<string>`. Based on example code and on debug output from the python scripts doing the same thing, I made the reading method as following:

```cpp
// ...
typedef map<int16_t, variant<vector<uint8_t>>> manufacturer_data_t;
map<string, std::variant<int16_t, string, manufacturer_data_t>> changedProperties;
vector<string> invalidatedProperties;
string interface;
msg.read(interface, changedProperties, invalidatedProperties);
// ...
```

However, I encounter an `std::bad_variant_access` exception when trying to access `variant`s in this map. Variant's `index()` would always return `0` which corresponds to `int16_t` in our case. For the 'ManufacturerData' field it does not make any sense, since it should contain a dictionary. 

Could you please give any clue on where to look for a possible mistake? 
Also, is there a reliable way to get raw message data in order to introspect its structure?

Thanks in advance!

**Comment by vsabadazh** [comment]
I think it'd be useful to attach some output from `dbus-monitor` here:

```
signal time=1616662573.310150 sender=:1.3 -> destination=(null destination) serial=131966 path=/org/bluez/hci0/dev_04_EE_03_C1_C0_AB; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.bluez.Device1"
   array [
      dict entry(
         string "RSSI"
         variant             int16 -61
      )
      dict entry(
         string "TxPower"
         variant             int16 -59
      )
      dict entry(
         string "ManufacturerData"
         variant             array [
               dict entry(
                  uint16 1034
                  variant                      array of bytes [
                        01 ab c0 c1 03 ee 04 13 01 00
                     ]
               )
            ]
      )
   ]
   array [
   ]
```

**Comment by williamspatrick** [comment]
Hi @vsabadazh .  It looks like your problem is a subtle `uint16` vs `int16`.

Your code had:
```
typedef map<int16_t, variant<vector<uint8_t>>> manufacturer_data_t;
```

But "ManufacturerData" had:
```
         variant             array [
               dict entry(
                  uint16 1034
```

**Comment by vsabadazh** [comment]
Hi @williamspatrick, thank you so much for your help! You were absolutely right, I've used the wrong type in client code.
