### ISSUE TITLE
Issues with examples

### ISSUE THREAD

**Issue by paulnegz** [openbmc/sdbusplus#64]
I am new to sdbusplus and decided to try out the examples in the examples directory. I cloned the sdbusplus repo on my ubuntu system and built it with the commands
```
meson build
cd build
ninja
ninja test
ninja install
cd tools
./setup.py install
```
Then in an an attempt to run the examples I used the command 
`g++ -o main.exe list-users.cpp`

I get a couple of error shown in the attached image 
![EXAMPLE](https://user-images.githubusercontent.com/37233089/123174630-087ad900-d446-11eb-8306-8bf41bfd99d2.JPG)
![log](https://user-images.githubusercontent.com/37233089/123174634-09136f80-d446-11eb-843b-fa9baaa8932c.JPG)

**Comment by williamspatrick** [comment]
You need —std=c++17 (or better would be c++20). Which ever standard your host compiler is defaulting to doesn’t have string_view defined.  GCC is reporting that in the attached failure log.
