### ISSUE TITLE
CMake support?

### ISSUE THREAD

**Issue by mrsaleh** [openbmc/sdbusplus#66]
Hi 
Do you have any plan to add CMake support?
great library , BTW.

**Comment by williamspatrick** [comment]
I hadn't planned on it, since we tend to use meson for all of our projects.  You should be able to integrate it into a CMake repository fairly easily with ExternalProject.  Is there some advantage of us having native CMake support?

**Comment by mrsaleh** [comment]
It's more convenient to use a CMake library, and CMake is everywhere these days. Also, I didn't know about ExternalProject. :-)
Thanks.

**Comment by williamspatrick** [comment]
If someone is especially interested in working on a CMake implementation, I'd consider reviewing it, but it isn't especially interesting to me.  I think a higher-value piece of work would be to implement a version of `sdbus++-gen-meson` (https://github.com/openbmc/sdbusplus/blob/master/tools/sdbus%2B%2B-gen-meson) but for CMake.  I'm going to close this task as I don't think there is anyone presently interested in working on this.
