### ISSUE TITLE
Adoption of string_view?

### ISSUE THREAD

**Issue by vsytch** [openbmc/sdbusplus#75]
Majority of the sdbus++ APIs only accept things like names and paths as `const std::string&`. This makes it impossible to pass arguments of the type `std::string_view` to them as there is no implicit conversion present.

A solution to the above problem would be to simply replace the usage of `const std::string&` with `std::string_view`, as these two types behave identically. This would result in an ABI breakage though, is that a concern?

**Comment by wak-google** [comment]
It's trivial to drop in stdplus::const_zstring / stdplus::zstring_view to make it easier to accept `const char *` and `const std::string&` calls directly. But it would not give you `std::string_view` conversion directly as it's not free. I was going to change a small number callsites and see how it goes.

**Comment by williamspatrick** [comment]
I don't have any concern about ABI.  We don't really distribute a versioned .so in a meaningful way right now.

I have started to do some of those conversions but I didn't get very far.  I really don't like that some APIs take char* and some take string and some take string_view.  I'd like to get something more consistent as well.

I think the primary concern is that string_view isn't certain to be NUL-terminated, so then we have a bit of extra effort to ensure termination before calling the underlying sd-bus calls.
