### ISSUE TITLE
return error on property changes ?

### ISSUE THREAD

**Issue by frsauvage** [openbmc/sdbusplus#79]
Hi,
I cannot implement the following use case:

From bmcweb code, I set RequestedPowerTransition.
From requestedPowerTransition (phosphor-state-manager code) , I have a bad condition and I reject the transition.

==> How can I throw something (error code, exception ?) back to bmcweb in order to know what happened ?

I was not able to add a "exceptions:" part in yaml around a property to create and throw a specific exception while getting / setting a property, like I did with methods.

I need to declare (and return) an exception while a property changed.

![image](https://user-images.githubusercontent.com/23147820/233828550-6934809f-649c-4d13-8af5-5237a9f3d3f2.png)

Maybe I should post my question to phosphor-bus-interfaces, because it is a generation problem,

Best regards,
Francine

**Comment by williamspatrick** [comment]
I might be misunderstanding the question.

The sdbusplus generator has support for the property in the YAML having errors associated with it.  See https://github.com/openbmc/sdbusplus/blob/cca2ec4b2a76f8c12da7edd4a2ead6fc9a3ed4dc/tools/sdbusplus/templates/property.prototype.hpp.mako#L96 .

It looks like the RequestedPowerTransition property doesn't currently have any `errors` associated with it.  If you find some that you think should be added, I think you can propose them there.  See https://github.com/openbmc/phosphor-dbus-interfaces/blob/927d0930ca70a3767ffae6ae092d51d3a8415250/yaml/xyz/openbmc_project/State/Chassis.interface.yaml#L7

**Comment by frsauvage** [comment]
I am so grateful, @williamspatrick , you perfectly understood and answered to my question.

**Comment by frsauvage** [comment]
@williamspatrick
Sorry to reply in a closed ticket, bad practice, worst way to do...

I tested ChatGPT on my question and the answer is insterested : 
is it supported to add "sdbus / exceptions" entries in a yaml file ?

sdbus:
  exceptions:

![image](https://user-images.githubusercontent.com/23147820/234554195-b3788bec-e564-4399-9281-80c2aa894ff9.png)

**Comment by williamspatrick** [comment]
> I planed to patch an "exceptions:" entry in the Chassis model yaml file, but if it is supported, I would prefer sdbus exceptions entry.

it should be “errors:” and not “exceptions:”.

 https://github.com/openbmc/sdbusplus/blob/master/docs/yaml/interface.md#properties

The example above shows how to add an “error” to a property.

**Comment by frsauvage** [comment]
So nice to answer me, many thanks @williamspatrick :-)
