### ISSUE TITLE
broken build on ubuntu 22

### ISSUE THREAD

**Issue by gabonator** [openbmc/sdbusplus#82]
Commit https://github.com/openbmc/sdbusplus/commit/798848de8fae11ecbb1fd17b66be5060ab6b82a3 upgrades the c++ standard to `cpp_std=c++23`. That means I cannot build it with gcc-12 on ubuntu 22 anymore. Not saying that all submodules in `entity-manager` point to head, so it is difficult to build whole environment (entity-manager, phosphor-objmgr, dbus-sensors) automatically. What is the point of upgrading the standard when there is not a single feature from it used in these projects? Any plans to keep backward compatibility and using commit references in meson subproject `.wrap` files?

**Comment by williamspatrick** [comment]
> That means I cannot build it with gcc-12 on ubuntu 22 anymore.

The project uses gcc-13 for CI.  We currently only have compile guarantees for the environment exposed by the Docker container used by CI from openbmc-build-scripts.  If you'd like to see broader compile guarantees we would need someone to contribute that.   

> What is the point of upgrading the standard when there is not a single feature from it used in these projects?

Repos like `entity-manager` also have commits for moving to C++23 pending.  There are commits that have already landed in the organization for leveraging C++23 features.  More will come as we have all the dependent projects of sdbusplus, for example, also moved to C++23.  [I can't leverage C++23 features if there are repositories not able to compile with C++23, after  all.]

> Not saying that all submodules in entity-manager point to head

The only subproject not pointing to HEAD in entity-manager's wraps is Boost.  If you find any wraps that are not HEAD, but are pointing to an openbmc-organization repository, please let me know and I will get those fixed.  None of the subproject wraps should point at a non-HEAD version.

> Any plans to keep backward compatibility and using commit references in meson subproject .wrap files?

There is not.

If you are unable to install a secondary GCC (and/or Clang) tool-chain on your Linux distribution, you should consider using the Docker container from openbmc-build-scripts (`scripts/build-unit-test-docker`).  This can be used for all compilation and linting.
