### ISSUE TITLE
How to delete one object/manager path under a object server

### ISSUE THREAD

**Issue by yongyuandeconan** [openbmc/sdbusplus#89]
Hi

I'm trying to write a new app based on example/asio-example.cpp. Create io context and object_server then add manager, interface and register properties according to reading one json file.
Since that json file may change frequently dbus objects are dynamic. I want a call which can delete object path such as  /xyz/openbmc_project/inventory/system/drive/nvme1. But no such method under include/sdbusplus/asio/object_server class (only _remove_interface_ , _add_interface_ , _add_manager_, no just as _remove_manager_). 
And I also try to use method _emit_object_removed_ from bus class under include/sdbusplus/bus.hpp but it doesn't work (just as systemBus->emit_object_removed(/xyz/openbmc_project/inventory/system/drive/nvme1)).
So I'd like to know is there any way to do such task. 

Thanks.

**Comment by williamspatrick** [comment]
My understanding with the ASIO code is that you would pair the add_interface / remove_interface calls. The ASIO code doesn’t seem to have a concept of a complete object, but just interfaces at paths. Removing all of the interfaces at a path is the same as removing the whole object, from a dbus perspective, except with potentially more signals if there are multiple interfaces.

You should probably consider the ASIO code end of life.  For new code it would be better to use the newer async code with co-routines.
