### ISSUE TITLE
Support enums within containers

### ISSUE THREAD

**Issue by milindur** [openbmc/sdbusplus#9]
Currently it is not supported to use enums within another container, e,.g. dict[string, enum[self.State]].

**Comment by williamspatrick** [comment]
This is in progress.

**Comment by williamspatrick** [comment]
The majority of this is now merged. There are some subtle edge cases that might not work and result in missing includes, when using an enumeration defined in another interface, but I’ll fix those up in the near future. Going to mark this closed as it should be functional for most cases.
