### ISSUE TITLE
Using sdbusplus consumes too much CPU I/O resources

### ISSUE THREAD

**Issue by renweihang** [openbmc/sdbusplus#92]
The following is the debugging code.
Using sdbusplus：
![image](https://github.com/openbmc/dbus-sensors/assets/24242110/21cf4744-3900-4c00-8c42-1a019d6fb0cb)

Not using sdbusplus：
![image](https://github.com/openbmc/dbus-sensors/assets/24242110/b3def64e-f6fd-40f4-b13f-e754c5428cfc)

PS: The OpenBMC commit I am using is 6fddef299932b1270a799e78566e25daa911f742
      The sdbusplus commit I am using is ae22c6ac5135cb2faafb076a22c0f2e6f5158068

**Comment by williamspatrick** [comment]
Removing all the code from a daemon doesn't make this an sdbusplus problem.
