### ISSUE TITLE
Clarification on declaring sdbusplus::vtable::property getter function.

### ISSUE THREAD

**Issue by AithaTarun** [openbmc/sdbusplus#99]
How to use sdbusplus::vtable::property with a getter function in CPP class context.
get paramater is expecting sd_bus_property_get_t function pointer which of type 

typedef int (*sd_bus_property_get_t)(	sd_bus *bus,
 	const char *path,
 	const char *interface,
 	const char *property,
 	sd_bus_message *reply,
 	void *userdata,
 	sd_bus_error *ret_error);

how can I pass a CPP class method of same definition to  sdbusplus::vtable::property ?
Getting errors on incompatibility if passing lamba function also.

**FYI : Can't create static functions, need this getter instance for each class separately.**

Please help me out here

**Comment by williamspatrick** [comment]
You have to make a static function that casts the user data to `this` and calls a member function.  There is no other way to get a C++ style member function to work with a C calling convention. 

This is even how the generated bindings have to do it. 

https://github.com/openbmc/sdbusplus/blob/ebe01794cde319728a1734d88f9ff61f597c707b/tools/sdbusplus/templates/property.aserver.callback.hpp.mako#L12
